project:
  type: website

website:
  title: "An Ly"
  favicon: profile.jpg
  description: "An Ly's Profile"
  navbar:
    left:
      - text: Profile
        href: profile.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: cv.qmd
      - text: Contact
        href: contact.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


